### PR TITLE
Fix MMR 404

### PR DESCRIPTION
**Pull request by Henrik-3**
Fixes that the MMR Function returns 404

### CODE REVIEW

**Comment by Henrik-3** [comment]
#14 Related

**Review by Xyrrm — COMMENTED** [review]
This also fixes #13 thanks @Henrik-3!

**Comment by liamcottle** [comment]
Thanks! Just a note for the future, so you don't have to wait for client version updates to be merged in, you can set your own client version on the api object.

```
const Valorant = require('@liamcottle/valorant.js');
const valorantApi = new Valorant.API(Valorant.Regions.AsiaPacific);
valorantApi.client_version = 'release-03.00-shipping-22-574489';
```

Similar issue: https://github.com/liamcottle/valorant.js/issues/12#issuecomment-820507660

**Comment by Henrik-3** [comment]
Ah yeah right, forgot about that

**Pull request merged**
